### ISSUE TITLE
ToDo: Frankfurter Map-Web­prä­senz

### ISSUE THREAD

**Issue by oszilloskop** [freifunk-ffm/ToDo-Liste#48]
Hier werden emotionslos Auffälligkeiten der Frankfurter Map aufgeführt.
Da es sich bei der Frankfurter Map um ein Konglomerat von mehreren Dingen handelt (Yanic, Meshviewer, Web-Server, etc.) sind die folgenden Punkte wohl nicht nur Frankfurt-relevant.
 
- [ ] Auf der Netztopologie-Graphenseite werden nur Knoten dargestellt, welche mit mindestens einem weiteren Knoten meshen. Isolierte Knoten (mesh-los) werden nicht dargestellt. (Beispiel: https://map.ffm.freifunk.net/#/graph)
- [ ] Auf der Hauptseite der Map hat das Eingabefeld "Knotenfilter" keine Funktion
- [ ] Yanic mag das Firmware-Package ffffm-additional-wifi-json-info nicht. 
- [ ] Keine Knoten-.Statusinformationen zum verwendeten WLAN-Kanal
- [ ] Keine Knoten-Statusinformationen zum verwendeten "Next-Hop"
- [ ] Ist auf der Landkartenansicht ein Knoten markiert worden und wird dann auf die Netztopologie-Graphenseite gewechselt, so wird der vorher markierte Knoten nicht zentriert dargestellt. Der Knoten ist dann meist schwer zu finden.
- [ ] Ist auf der Netztopologie-Graphenseite ein Knoten markiert (weiß umrandet) so wird dieser automatisch visual demarkiert (keine weisse Umrandung mehr) wenn sich die Netztopologie-Graphenseite auf Grund neuer JSON-Daten neuorganisiert (alle paar Minuten). Die Netztopologie-Graphenseite behandelt diesen Knoten aber noch so als ob er markiert ist. Er kann aber nicht mehr duch einen Mausklcik markiert werden. Dieses ist nur über den Umweg möglich, dass zuvor ein beliebig anderer Knoten markiert wird.
- [ ] Ist auf der Netztopologie-Graphenseite ein Knoten markiert (weiß umrandet), und wird im Browser (hier Chrome) auf ein anderes Tab gewechselt und dort für einige Minuten verweilt, so wird bei einem Rückwechseln auf die Netztopologie-Graphenseite keine Netzwerktopologie mehr angezeigt (komplett Schwarze darstellung). Dieses passiert aber wohl nur, wenn zwischendurch die JSAN-Daten aktualisiert wurden.
- [ ] ... Weitere Auffälligkeiten bitte eigenständig hier aufführen.

Wie gesagt, nicht alles ist für das Frankfurter Webteam relevant.

**Comment by MyIgel** [comment]
Die Issues sollten mal mit https://github.com/ffrgb/meshviewer/issues abgeglichen werden

**Comment by oszilloskop** [comment]
Laut Aussage von @skorpy2009 muss die Firmware angepasst werden. Was machen wir später mit alten Knoten, welche evtl. nicht updaten? Zerschiessen die die Map dann?

**Comment by christf** [comment]
On Wed, May 10, 2017 at 10:50:08AM -0700, oszilloskop wrote:
>Laut Aussage von @skorpy2009 muss die Firmware angepasst werden. Was machen wir
>später mit alten Knoten, welche evtl. nicht updaten? Zerschiessen die die Map
>dann?
Warum brauchen wir das Update?

viele Grüße

Christof

-- 
()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments

**Comment by oszilloskop** [comment]
Die JSON-Daten, welche vom Package ffffm-additional-wifi-json-info kommen (WLAN-Kanal, Next-Hop, etc.) , überfordern wohl Yanic.
Damit die Map funktioniert ist Yanic z.Z. von @skorpy2009 gepatched worden. (Ob das jetzt ein Patch oder ein böser Hack ist, dass  kann nur @skorpy sagen.)
Er würde sich auf jeden Fall gerne an den Yanic Master-Branch hängen. Da ist dann aber ein zusätzlicher Frankfurter Patch wohl so in seinem Sinne.

**Comment by oszilloskop** [comment]
Obige Liste wurde aktualisiert.

**Comment by oszilloskop** [comment]
Obige Liste wurde aktualisiert.

**Comment by skorpy2009** [comment]
Wegen Zoom uns so @oszilloskop https://meshviewer.gitbooks.io/documentation/content/config_json.html#nodezoom-integer

**Comment by wahram** [comment]
Wenn man lange genug wartet, scheint der (2.) Offline-Knoten mit dem Namen fastd6 wieder zu verschwinden.

**Comment by oszilloskop** [comment]
Auf der Freifunk-Deutschlandkarte klafft immer noch ein Loch über Frankfurt.
Siehe: https://www.freifunk-karte.de

**Comment by wahram** [comment]
Wir sind auf der Karte zu sehen -> fixed!
Den Issue mit dem Zoom kann man beheben, ist die Frage, ob das nötig ist?

**Comment by skorpy2009** [comment]
@oszilloskop was ist hier der Status?

**Comment by oszilloskop** [comment]
@skorpy2009 
Siehe ersten Eintrag: https://github.com/freifunk-ffm/ToDo-Liste/issues/48#issue-227739342
